namespace: "configmap-updater-system"

destinationCluster:
  enabled: true
  name: bf-destination
  pollInterval: 5m
  kubeconfig:
    enabled: true
    name: "306"
    key: "kubeconfig"
    data: |
      # TODO: 실제 kubeconfig를 넣어주세요.
      <PASTE_KUBECONFIG_HERE>
