{{- if and .Values.destinationCluster.enabled .Values.destinationCluster.kubeconfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.destinationCluster.kubeconfig.name }}
  namespace: {{ include "configmap-updater.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "configmap-updater.fullname" . }}
    app.kubernetes.io/part-of: configmap-updater
type: Opaque
stringData:
  {{ .Values.destinationCluster.kubeconfig.key }}: |
{{ .Values.destinationCluster.kubeconfig.data | nindent 4 }}
---
{{- end }}

{{- if .Values.destinationCluster.enabled }}
apiVersion: ops.ops.example.io/v1alpha1
kind: DestinationCluster
metadata:
  name: {{ .Values.destinationCluster.name }}
  namespace: {{ include "configmap-updater.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "configmap-updater.fullname" . }}
    app.kubernetes.io/part-of: configmap-updater
spec:
  kubeconfigSecretRef:
    name: {{ .Values.destinationCluster.kubeconfig.name }}
    key: {{ .Values.destinationCluster.kubeconfig.key }}
  pollInterval: {{ .Values.destinationCluster.pollInterval }}
{{- end }}
